server:
  port: ${SERVER_PORT:8080}

spring:
  webflux:
    base-path: /api

management:
  endpoints:
    web:
      exposure:
        include: "*"

github:
  url: https://api.github.com
  token: ${GITHUB_TOKEN}
